spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member-service/members
            - Method=POST
          filters:
            - StripPrefix=1
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member-service/members/login
            - Method=POST
          filters:
            - StripPrefix=1

        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member-service/**
          filters:
            - StripPrefix=1
            - AuthorizationHeaderFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
            - AuthorizationHeaderFilter

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
          filters:
            - StripPrefix=1
            - AuthorizationHeaderFilter


        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/delivery-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}

access:
  key: userkeyaccesskeyaldsnalksdnlkjasdfnlkasndlkfasnlkd