spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service  # ? ??? ID
          uri: lb://user-service  # ??? ?? (Eureka?? ??? ??)
          predicates:
            - Path=/user-service/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}

